### ISSUE TITLE
To perform this lab we require azure cli older 2.0.68 version

### ISSUE THREAD

**Issue by GhumanNavneet** [microsoft/MCW-High-Performance-Computing#22]
In this lab we are installing latest version for Azure CLI, which is not allowing to perform lab. Show below warning while running any azure batch command : 
Unable to load extension 'azure-cli-batch-extension'. 

Same lab perform with older CLI 2.0.68 version and able to perform the lab.

**Comment by GhumanNavneet** [comment]
Any update on this?

**Comment by DawnmarieDesJardins** [comment]
@joelhulen @timahenning 
Hello!  Please review and advise.

**Comment by timahenning** [comment]
Hi Dawnmarie,

The team is looking into it.

Tim

**Comment by DawnmarieDesJardins** [comment]
Addressed in recent merge - closing.
