### ISSUE TITLE
Exercise 2: Task 2: Stage the sample videos to process

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-High-Performance-Computing#25]
[Exercise 2: Task 2: Step 1:](https://github.com/microsoft/MCW-High-Performance-Computing/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20High%20Performance%20Computing.md#task-2-stage-the-sample-videos-to-process) The video link given here is broken.

Here is the video link and the error:
**https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_30mb.mp4**

![image](https://user-images.githubusercontent.com/50323628/64647213-3a1fdd00-d436-11e9-86b4-6c0c3c46aa77.png)

Kindly check this.

Thank You,
Seerat

**Comment by timahenning** [comment]
Thank you for letting us know.  We will look into it.

Tim

**Comment by SeeratArora** [comment]
Hi @timahenning 
Do we have any update?

**Comment by SeeratArora** [comment]
Hi @DawnmarieDesJardins 
Hope you are doing well.

Do we have updates on this issue?

**Comment by timahenning** [comment]
We are planning to have this issue addressed by EOD. 

Tim

**Comment by givenscj** [comment]
Hi there, I just checked and the video is there.  They may have had a temporary issue with their website the day you tried it.

**Comment by SeeratArora** [comment]
Hi @givenscj 
Yeah I checked the URL, now the video is there. Maybe yes it was a temporary issue.

Thanks!

**Comment by DawnmarieDesJardins** [comment]
Thanks all!  Closing as resolved.
